name: "Action PR to Md"
description: "Action to output a list of PRs to a Markdown file."
author: "ryohidaka"
inputs:
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "file-text"
  color: "green"
